### ISSUE TITLE
minChars three and below are ignored

### ISSUE THREAD

**Issue by bwente** [modxcms/SimpleSearch#11]
I have a few TIA (Three Initial Abbreviations) that I would like to search for, but the minChars seemed to be ignored. I have tried both as a parameter and as a property, and still no luck. If I make it higher it seems to respect those values.

**Comment by TheBoxer** [comment]
Hi,

I am sorry, but I can't reproduce this issue. I added &minChars=`1` to the SimpleSearch snippet call and when searching for `te` it worked fine. Without the setting I was receiving no results.

**Comment by vierkantemeter** [comment]
Hi, I was having the exact same problem. When searching for "PDF", no results are found. After some investigation, it turned out the mysql setting ```ft_min_word_len``` was set to 4. When lowering this to 2, everything works again!
