### ISSUE TITLE
"exclude" parameter has no effect

### ISSUE THREAD

**Issue by boformer** [modxcms/SimpleSearch#16]
This forum thread explains the issue: http://forums.modx.com/thread/86785/simplesearch-exclude-property-doesn-039-t-work---doesn-039-t-build-the-right-query

**Comment by boformer** [comment]
I think I identified the problem.

This code segment provides the functionality:
https://github.com/modxcms/SimpleSearch/blob/master/core/components/simplesearch/model/simplesearch/driver/simplesearchdriverbasic.class.php#L172-L185

The "exclude" parameter is only processed if the "ids" parameter is set.

**Comment by pyrographics** [comment]
I'm not seeing where the &ids parameter has any effect either.

**Comment by rainbowtiger** [comment]
Here's the fix. On line 191 of core/components/simplesearch/model/simplesearch/driver/simplesearchdriverbasic.class.php, add this line:
`$c->where(array("id:NOT IN" => explode(',', $exclude)),xPDOQuery::SQL_AND,null,$whereGroup);`
