### ISSUE TITLE
Modx3: Resources cant be saved with SimpleSearch 3.0.0-alpha

### ISSUE THREAD

**Issue by bYemma** [modxcms/SimpleSearch#52]
In the save process of a resource there's a 500 server error. The MySQL driver class is not found. PHP 7.4, MODX 3.0.1

`AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class '\\SimpleSearch\\Driver\\SimpleSearchDriverBasic_mysql' not found in [...]/core/components/simplesearch/model/simplesearch/simplesearch.class.php:135\nStack trace:\n#0 [...]/core/cache/includes/elements/modx/revolution/modplugin/1.include.cache.php(40): SimpleSearch->loadDriver()\n#1 [...]/core/src/Revolution/modScript.php(88): include('...')\n#2 [...]/core/src/Revolution/modX.php(1706): MODX\\Revolution\\modScript->process()\n#3 [...]/core/src/Revolution/Processors/Resource/Update.php(893): MODX\\Revolution\\modX->invokeEvent()\n#4 [...]/core/src/Revolution/Processors/Resource/Update.php(677): MODX\\Revolution\\Processors\\Resource\\Update->fireDeleteEvent()\n#5 [...]/core/src/Revolution/Processors/Model/UpdateProcessor.php(92): MODX\\Revolution\\Processors\\Resource\\Update->afterSave()\n#6 ...'`

**Comment by bYemma** [comment]
It is related to #51 
When changing the system setting "simplesearch.driver_class" to "\SimpleSearch\Driver\SimpleSearchDriverBasic" to address the above problem, the resource can't saved anymore.

**Comment by halftrainedharry** [comment]
How old was the _SimpleSearch_ version you updated from?
I believe a plugin "simplesearchindexer" was once a part of _SimpleSearch_, but has been removed long ago (probably with version 2.0.0).
It seems that this plugin still exists on your installation. Deactivate or delete it.

**Comment by bYemma** [comment]
I think the Plugin was first installed in 2014. But the updates were done up to now.

Thank you for your hint. I'll give this a look.

**Comment by bYemma** [comment]
Complete uninstall and new install of SimpleSearch does help. Thank you!

**Comment by bYemma** [comment]
@halftrainedharry Deleting the plugin "simplesearchindexer" does the work! Thank you!
