### ISSUE TITLE
SimpleSeacr error with ModX 3.0.3

### ISSUE THREAD

**Issue by sandiphw** [modxcms/SimpleSearch#60]
I am getting the following fatal error with ModX Revo 3.0.3 & SimpleSearch 3.0.0 beta.  PHP version 8.1.2.

_[09-Jun-2023 17:22:34 UTC] PHP Fatal error:  Uncaught MODX\Revolution\Services\NotFoundException: Dependency not found with key pdotools. in /var/www/html/abcd.com/core/src/Revolution/Services/Container.php:34
Stack trace:
#0 /var/www/html/abcd.com/core/components/simplesearch/src/SimpleSearch.php(55): MODX\Revolution\Services\Container->get()
#1 /var/www/html/abcd.com/core/cache/includes/elements/modx/revolution/modsnippet/36.include.cache.php(40): SimpleSearch\SimpleSearch->getChunk()
#2 /var/www/html/abcd.com/core/src/Revolution/modScript.php(88): include('...')
#3 /var/www/html/abcd.com/core/src/Revolution/modParser.php(505): MODX\Revolution\modScript->process()
#4 /var/www/html/abcd.com/core/src/Revolution/modParser.php(218): MODX\Revolution\modParser->processTag()
#5 /var/www/html/abcd.com/core/src/Revolution/modResource.php(521): MODX\Revolution\modParser->processElementTags()
#6 /var/www/html/abcd.com/core/src/Revolution/modResource.php(469): MODX\Revolution\modResource->parseContent()
#7 /var/www/html/abcd.com/core/src/Revolution/modResponse.php(72): MODX\Revolution\modResource->prepare()
#8 /var/www/html/abcd.com/core/src/Revolution/modRequest.php(154): MODX\Revolution\modResponse->outputContent()
#9 /var/www/html/abcd.com/core/src/Revolution/modRequest.php(138): MODX\Revolution\modRequest->prepareResponse()
#10 /var/www/html/abcd.com/core/src/Revolution/modX.php(1499): MODX\Revolution\modRequest->handleRequest()
#11 /var/www/html/abcd.com/index.php(63): MODX\Revolution\modX->handleRequest()
#12 {main}
  thrown in /var/www/html/abcd.com/core/src/Revolution/Services/Container.php on line 34_

I have tested with:
[[!SimpleSearchForm]]
<h2>Results</h2>
[[!SimpleSearch]]

Can you please suggest?

Regards,

Sandip

**Comment by toro-terminator** [comment]
I got the same problem after upgrading SimpleSearch. MODX 3.0.3

```
[12-Jun-2023 15:26:06 UTC] PHP Fatal error:  Uncaught MODX\Revolution\Services\NotFoundException: Dependency not found with key pdotools. in /www/core/src/Revolution/Services/Container.php:34
Stack trace:
#0 /www/core/components/simplesearch/src/SimpleSearch.php(55): MODX\Revolution\Services\Container->get()
#1 /www/core/cache/includes/elements/modx/revolution/modsnippet/28.include.cache.php(40): SimpleSearch\SimpleSearch->getChunk()
#2 /www/core/src/Revolution/modScript.php(88): include('...')
#3 /www/core/src/Revolution/modParser.php(505): MODX\Revolution\modScript->process()
#4 /www/core/src/Revolution/modParser.php(218): MODX\Revolution\modParser->processTag()
#5 /www/core/src/Revolution/modResource.php(521): MODX\Revolution\modParser->processElementTags()
#6 /www/core/src/Revolution/modResource.php(469): MODX\Revolution\modResource->parseContent()
#7 /www/core/src/Revolution/modResponse.php(72): MODX\Revolution\modResource->prepare()
#8 /www/core/src/Revolution/modRequest.php(154): MODX\Revolution\modResponse->outputContent()
#9 /www/core/src/Revolution/modRequest.php(138): MODX\Revolution\modRequest->prepareResponse()
#10 /www/core/src/Revolution/modX.php(1499): MODX\Revolution\modRequest->handleRequest()
#11 /www/index.php(63): MODX\Revolution\modX->handleRequest()
#12 {main}
  thrown in /www/core/src/Revolution/Services/Container.php on line 34
```

**Comment by sandiphw** [comment]
Thanks. Its working now.
